# Generated by Django 3.0.5 on 2020-05-02 22:11

from django.conf import settings
import django.contrib.postgres.fields.jsonb
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('actions', '0011_auto_20200317_1055'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data', '0006_dataset_hash_version'),
        ('misc', '0007_auto_20200120_1223'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodConsumption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, help_text='Long name', max_length=255)),
                ('json', django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='Structured data, formatted in a user-defined way', null=True)),
                ('amount', models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(limit_value=0)])),
                ('date_time', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('housing_subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='misc.HousingSubject')),
                ('lab_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BehavioralTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, help_text='Long name', max_length=255)),
                ('json', django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='Structured data, formatted in a user-defined way', null=True)),
                ('reward_type', models.CharField(blank=True, choices=[('juice', 'Juice')], default=None, max_length=255)),
                ('version', models.CharField(blank=True, help_text='generating software revision', max_length=64, null=True)),
                ('date_time', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('weight', models.FloatField(help_text='Weight in Kg', validators=[django.core.validators.MinValueValidator(limit_value=0), django.core.validators.MaxValueValidator(limit_value=35)])),
                ('food', models.FloatField(help_text='Food in Ml', validators=[django.core.validators.MinValueValidator(limit_value=50), django.core.validators.MaxValueValidator(limit_value=1500)])),
                ('food_note', models.TextField(blank=True, help_text='If supplemented make note')),
                ('menstration', models.BooleanField(default=False)),
                ('general_comments', models.TextField(blank=True)),
                ('task_sequence', models.PositiveSmallIntegerField(blank=True, help_text='Indicates the relative position of a task within the session it belongs to')),
                ('dataset_type', models.ManyToManyField(blank=True, to='data.DatasetType')),
                ('lab_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='actions.Session')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
