# Generated by Django 3.0.5 on 2020-05-20 15:50

from django.conf import settings
import django.contrib.postgres.fields.jsonb
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data', '0006_dataset_hash_version'),
        ('subjects', '0006_auto_20200317_1055'),
        ('misc', '0007_auto_20200120_1223'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('actions', '0011_auto_20200317_1055'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelRecording',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alive', models.BooleanField(default=False)),
                ('number_of_cells', models.CharField(blank=True, choices=[(1, 'nothing'), (2, 'maybe 1 cell'), (3, '1 good cell'), (4, '2+ good cells')], default='', max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Electrode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('turn', models.FloatField()),
                ('millimeters', models.FloatField(blank=True, null=True)),
                ('impedance', models.FloatField(blank=True, null=True)),
                ('units', models.CharField(blank=True, choices=[('none', '0'), ('few', '1'), ('lots', '2')], default='', max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('subject', models.ForeignKey(help_text='The subject on which the electrode is', null=True, on_delete=django.db.models.deletion.SET_NULL, to='subjects.Subject')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('json', django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='Structured data, formatted in a user-defined way', null=True)),
                ('name', models.CharField(blank=True, help_text='Task name', max_length=255)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, choices=[('task1', 'Task 1')], default=None, max_length=255)),
                ('reward_type', models.CharField(blank=True, choices=[('juice', 'Juice')], default=None, max_length=255)),
                ('maze_type', models.CharField(blank=True, choices=[('Y-maze', 'Y-maze'), ('calibration', 'Calibration')], max_length=125)),
                ('original_task', models.CharField(blank=True, help_text='Task version', max_length=255, null=True)),
                ('first_version', models.BooleanField(default=True)),
                ('version', models.CharField(blank=True, default='1', help_text='Task version', max_length=255, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SubjectFood',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, help_text='Long name', max_length=255)),
                ('json', django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='Structured data, formatted in a user-defined way', null=True)),
                ('amount', models.FloatField(blank=True, null=True)),
                ('date_time', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('subject', models.ForeignKey(help_text='The subject on which this action was performed', null=True, on_delete=django.db.models.deletion.SET_NULL, to='subjects.Subject')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='STLFile',
            fields=[
                ('dataset_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='data.Dataset')),
                ('stl_file', models.CharField(blank=True, help_text='Path to STL file', max_length=1000)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('subject', models.ForeignKey(help_text='The subject on which the electrode is', null=True, on_delete=django.db.models.deletion.SET_NULL, to='subjects.Subject')),
            ],
            options={
                'abstract': False,
            },
            bases=('data.dataset',),
        ),
        migrations.CreateModel(
            name='StartingPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField(null=True)),
                ('y', models.FloatField(null=True)),
                ('z', models.FloatField(null=True)),
                ('orientation', models.CharField(blank=True, max_length=128)),
                ('notes', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('electrode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='starting_point', to='buffalo.Electrode')),
                ('lab_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SessionTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, help_text='Long name', max_length=255)),
                ('json', django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='Structured data, formatted in a user-defined way', null=True)),
                ('date_time', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('general_comments', models.TextField(blank=True)),
                ('task_sequence', models.PositiveSmallIntegerField(blank=True, help_text='Indicates the relative position of a task within the session it belongs to')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('dataset_type', models.ManyToManyField(blank=True, to='data.DatasetType')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='actions.Session')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='buffalo.Task')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProcessedRecording',
            fields=[
                ('dataset_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='data.Dataset')),
                ('source', models.CharField(blank=True, help_text='Path to source file', max_length=1000)),
                ('electrical_voltage_file', models.CharField(blank=True, help_text='Path to result file', max_length=1000)),
                ('date_time', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('lfp_band_1', models.FloatField(blank=True, null=True)),
                ('lfp_band_2', models.FloatField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('channel_recording', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='buffalo.ChannelRecording')),
            ],
            options={
                'abstract': False,
            },
            bases=('data.dataset',),
        ),
        migrations.CreateModel(
            name='FoodConsumption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, help_text='Long name', max_length=255)),
                ('json', django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='Structured data, formatted in a user-defined way', null=True)),
                ('amount', models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(limit_value=0)])),
                ('food', models.FloatField(default=None, help_text='Food in Ml', validators=[django.core.validators.MinValueValidator(limit_value=50), django.core.validators.MaxValueValidator(limit_value=1500)])),
                ('note', models.TextField(blank=True, help_text='If supplemented make note')),
                ('date_time', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('housing_subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='misc.HousingSubject')),
                ('lab_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DailyObservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('run', models.BooleanField(default=False)),
                ('general_comments', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('food', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='buffalo.FoodConsumption')),
                ('lab_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(help_text='The subject on which this action was performed', null=True, on_delete=django.db.models.deletion.SET_NULL, to='subjects.Subject')),
            ],
        ),
        migrations.AddField(
            model_name='channelrecording',
            name='electrode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='buffalo.Electrode'),
        ),
        migrations.AddField(
            model_name='channelrecording',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='actions.Session'),
        ),
        migrations.AddField(
            model_name='channelrecording',
            name='session_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='buffalo.SessionTask'),
        ),
        migrations.AddField(
            model_name='channelrecording',
            name='stl_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='buffalo.STLFile'),
        ),
    ]
