# Generated by Django 3.0.6 on 2020-06-10 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buffalo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stlfile',
            name='stl_file',
            field=models.FileField(upload_to='data'),
        ),
    ]
