# Generated by Django 3.0.5 on 2020-06-13 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buffalo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='channelrecording',
            old_name='riples',
            new_name='ripples',
        ),
    ]
