# Generated by Django 3.0.5 on 2020-05-04 21:52

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subjects', '0006_auto_20200317_1055'),
        ('buffalo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelRecording',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alive', models.BooleanField(default=False)),
                ('number_of_cells', models.CharField(blank=True, choices=[(1, 'nothing'), (2, 'maybe 1 cell'), (3, '1 good cell'), (4, '2+ good cells')], default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DailyObservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('general_comments', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Electrode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('turn', models.FloatField()),
                ('millimeters', models.FloatField(blank=True, null=True)),
                ('impedance', models.FloatField(blank=True, null=True)),
                ('units', models.CharField(blank=True, choices=[('none', '0'), ('few', '1'), ('lots', '2')], default='', max_length=255)),
                ('lfp_band_1', models.FloatField(blank=True, null=True)),
                ('lfp_band_2', models.FloatField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('daily_observation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='buffalo.DailyObservation')),
            ],
        ),
        migrations.CreateModel(
            name='STLFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stl_file', models.CharField(blank=True, help_text='Path to STL file', max_length=1000)),
            ],
        ),
        migrations.RemoveField(
            model_name='behavioraltask',
            name='food',
        ),
        migrations.RemoveField(
            model_name='behavioraltask',
            name='food_note',
        ),
        migrations.AddField(
            model_name='foodconsumption',
            name='food',
            field=models.FloatField(default=None, help_text='Food in Ml', validators=[django.core.validators.MinValueValidator(limit_value=50), django.core.validators.MaxValueValidator(limit_value=1500)]),
        ),
        migrations.AddField(
            model_name='foodconsumption',
            name='note',
            field=models.TextField(blank=True, help_text='If supplemented make note'),
        ),
        migrations.CreateModel(
            name='StartingPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField(null=True)),
                ('y', models.FloatField(null=True)),
                ('z', models.FloatField(null=True)),
                ('orientation', models.CharField(blank=True, max_length=128)),
                ('notes', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('electrode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='starting_points', to='buffalo.Electrode')),
                ('lab_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProcessedRecording',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(blank=True, help_text='Path to source file', max_length=1000)),
                ('result_file', models.CharField(blank=True, help_text='Path to result file', max_length=1000)),
                ('date_time', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('notes', models.TextField(blank=True)),
                ('channel_recording', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='buffalo.ChannelRecording')),
                ('lab_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='dailyobservation',
            name='food',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='buffalo.FoodConsumption'),
        ),
        migrations.AddField(
            model_name='dailyobservation',
            name='lab_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dailyobservation',
            name='subject',
            field=models.ForeignKey(help_text='The subject on which this action was performed', on_delete=django.db.models.deletion.CASCADE, related_name='buffalo_dailyobservations', to='subjects.Subject'),
        ),
        migrations.AddField(
            model_name='channelrecording',
            name='electrode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='buffalo.Electrode'),
        ),
        migrations.AddField(
            model_name='channelrecording',
            name='stl_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='buffalo.STLFile'),
        ),
        migrations.AddField(
            model_name='channelrecording',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='buffalo.BehavioralTask'),
        ),
    ]
