# Generated by Django 3.0.5 on 2020-06-13 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0011_auto_20200317_1055'),
        ('buffalo', '0002_auto_20200613_2244'),
    ]

    operations = [
        migrations.AddField(
            model_name='buffalosession',
            name='needs_review',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='WeighingLog',
            fields=[
                ('weighing_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='actions.Weighing')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='actions.Session')),
            ],
            options={
                'abstract': False,
            },
            bases=('actions.weighing',),
        ),
    ]
