# Generated by Django 3.0.5 on 2020-05-25 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buffalo', '0003_task_platform'),
    ]

    operations = [
        migrations.AddField(
            model_name='electrodeturn',
            name='turn',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='dailyobservation',
            name='subject',
            field=models.ForeignKey(help_text='The subject on which this action was performed', null=True, on_delete=django.db.models.deletion.SET_NULL, to='buffalo.BuffaloSubject'),
        ),
        migrations.AlterField(
            model_name='electrode',
            name='subject',
            field=models.ForeignKey(help_text='The subject on which the electrode is', null=True, on_delete=django.db.models.deletion.SET_NULL, to='buffalo.BuffaloSubject'),
        ),
        migrations.AlterField(
            model_name='stlfile',
            name='subject',
            field=models.ForeignKey(help_text='The subject on which the electrode is', null=True, on_delete=django.db.models.deletion.SET_NULL, to='buffalo.BuffaloSubject'),
        ),
        migrations.AlterField(
            model_name='subjectfood',
            name='subject',
            field=models.ForeignKey(help_text='The subject on which this action was performed', null=True, on_delete=django.db.models.deletion.SET_NULL, to='buffalo.BuffaloSubject'),
        ),
    ]
