# Generated by Django 3.0.7 on 2020-06-16 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buffalo', '0004_sessiontask_needs_review'),
        ('buffalo', '0003_auto_20200610_2034'),
    ]

    operations = [
    ]
