# Generated by Django 3.0.7 on 2020-06-19 17:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('buffalo', '0005_merge_20200616_1902'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buffalosession',
            name='dataset_type',
        ),
        migrations.AddField(
            model_name='sessiontask',
            name='start_time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.CreateModel(
            name='BuffaloDataset',
            fields=[
                ('dataset_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='data.Dataset')),
                ('file_name', models.CharField(blank=True, help_text='file name', max_length=255, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('session_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='buffalo.SessionTask')),
            ],
            options={
                'abstract': False,
            },
            bases=('data.dataset',),
        ),
    ]
