# Generated by Django 3.0.5 on 2020-05-26 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buffalo', '0005_sessiontask_dataset_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='TaskCategory',
        ),
        migrations.AlterField(
            model_name='sessiontask',
            name='task_sequence',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Indicates the relative position of a task within the session it belongs to', null=True),
        ),
    ]
