# Generated by Django 3.0.5 on 2020-10-14 17:21

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('buffalo', '0007_remove_task_dataset_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='NeuralPhenomena',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, help_text='Long name', max_length=255)),
                ('json', django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='Structured data, formatted in a user-defined way', null=True)),
                ('description', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='channelrecording',
            name='neural_phenomena',
            field=models.ManyToManyField(blank=True, to='buffalo.NeuralPhenomena'),
        ),
    ]
