# Generated by Django 3.0.5 on 2020-05-29 18:44

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0006_auto_20200317_1055'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('misc', '0007_auto_20200120_1223'),
        ('actions', '0011_auto_20200317_1055'),
        ('buffalo', '0007_auto_20200527_0351'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectrodeLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, help_text='Long name', max_length=255)),
                ('json', django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='Structured data, formatted in a user-defined way', null=True)),
                ('narrative', models.TextField(blank=True)),
                ('start_time', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('turn', models.FloatField()),
                ('impedance', models.FloatField()),
                ('notes', models.TextField(blank=True)),
                ('date_time', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BuffaloElectrodeLogSubject',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('buffalo.buffalosubject',),
        ),
        migrations.CreateModel(
            name='BuffaloElectrodeSubject',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('buffalo.buffalosubject',),
        ),
        migrations.RemoveField(
            model_name='electrode',
            name='impedance',
        ),
        migrations.DeleteModel(
            name='ElectrodeTurn',
        ),
        migrations.AddField(
            model_name='electrodelog',
            name='electrode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='buffalo.Electrode'),
        ),
        migrations.AddField(
            model_name='electrodelog',
            name='lab',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='misc.Lab'),
        ),
        migrations.AddField(
            model_name='electrodelog',
            name='location',
            field=models.ForeignKey(blank=True, help_text='The physical location at which the action was performed', null=True, on_delete=django.db.models.deletion.SET_NULL, to='misc.LabLocation'),
        ),
        migrations.AddField(
            model_name='electrodelog',
            name='procedures',
            field=models.ManyToManyField(blank=True, help_text='The procedure(s) performed', to='actions.ProcedureType'),
        ),
        migrations.AddField(
            model_name='electrodelog',
            name='subject',
            field=models.ForeignKey(help_text='The subject on which this action was performed', on_delete=django.db.models.deletion.CASCADE, related_name='buffalo_electrodelogs', to='subjects.Subject'),
        ),
        migrations.AddField(
            model_name='electrodelog',
            name='users',
            field=models.ManyToManyField(blank=True, help_text='The user(s) involved in this action', to=settings.AUTH_USER_MODEL),
        ),
    ]
