# Generated by Django 3.0.5 on 2020-10-25 13:41

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0011_auto_20200317_1055'),
        ('buffalo', '0008_auto_20201014_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='buffalosession',
            name='chamber_cleaning',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No'), ('n/a', 'N/A')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='buffalosession',
            name='pump_setting',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='MenstruationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, help_text='Long name', max_length=255)),
                ('json', django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='Structured data, formatted in a user-defined way', null=True)),
                ('menstruation', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='actions.Session')),
                ('subject', models.ForeignKey(help_text='The subject on which this action was performed', null=True, on_delete=django.db.models.deletion.SET_NULL, to='buffalo.BuffaloSubject')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
