# Generated by Django 3.0.5 on 2020-10-27 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buffalo', '0009_auto_20201025_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='buffalosession',
            name='unknown_user',
            field=models.CharField(blank=True, help_text='Unknown user initials', max_length=255, null=True),
        ),
    ]
