# Generated by Django 3.0.7 on 2020-10-27 06:44

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('buffalo', '0009_auto_20201025_1341'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuffaloDeviceSubject',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('buffalo.buffalosubject',),
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, help_text='Long name', max_length=255)),
                ('json', django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='Structured data, formatted in a user-defined way', null=True)),
                ('implantation_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('explantation_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('description', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('subject', models.ForeignKey(help_text='The subject on which the device is', null=True, on_delete=django.db.models.deletion.SET_NULL, to='buffalo.BuffaloSubject')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BuffaloElectrodeDevice',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('buffalo.device',),
        ),
        migrations.AddField(
            model_name='electrode',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device', to='buffalo.Device'),
        ),
    ]
