# Generated by Django 3.0.5 on 2020-10-28 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buffalo', '0010_buffalosession_unknown_user'),
        ('buffalo', '0010_auto_20201027_0644'),
    ]

    operations = [
    ]
