# Generated by Django 3.0.5 on 2020-10-29 16:27

from django.db import migrations


def create_subject_device(apps, schema_editor):
    subject_model = apps.get_model('buffalo', 'BuffaloSubject')
    device_model = apps.get_model('buffalo', 'Device')
    Electrode_model = apps.get_model('buffalo', 'Electrode')
    subjects = subject_model.objects.all()

    for subject in subjects:
        subject_device, _ = device_model.objects.get_or_create(
            subject=subject
        )
        if not subject_device.name:
            subject_device.name = "default"
            subject_device.save()
        subject_electrodes = Electrode_model.objects.filter(
            subject=subject
        )
        for subject_electrode in subject_electrodes:
            if subject_electrode.device is None:
                subject_electrode.device = subject_device
                subject_electrode.save()


class Migration(migrations.Migration):

    dependencies = [
        ('buffalo', '0010_auto_20201027_0644'),
    ]

    operations = [
        migrations.RunPython(create_subject_device),
    ]
