# Generated by Django 3.0.5 on 2020-10-29 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buffalo', '0011_merge_20201028_1940'),
        ('buffalo', '0012_auto_20201029_1627'),
    ]

    operations = [
    ]
