# Generated by Django 3.0.7 on 2020-11-04 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0011_auto_20200317_1055'),
        ('buffalo', '0013_merge_20201029_1155'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='channelrecording',
            unique_together={('electrode', 'session')},
        ),
    ]
