# Generated by Django 3.0.7 on 2020-11-09 13:11

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('buffalo', '0014_auto_20201104_1151'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuffaloAsyncTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, help_text='Long name', max_length=255)),
                ('json', django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='Structured data, formatted in a user-defined way', null=True)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('PEN', 'PENDING'), ('COM', 'COMPLETED'), ('ERR', 'ERROR')], default='PEN', max_length=3)),
                ('message', models.CharField(blank=True, default='', max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ElectrodeLogSTL',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, help_text='Long name', max_length=255)),
                ('json', django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='Structured data, formatted in a user-defined way', null=True)),
                ('is_in', models.BooleanField(default=False)),
                ('distance', models.FloatField(blank=True, default=None, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('electrodelog', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='electrodelogstl', to='buffalo.ElectrodeLog')),
                ('stl', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='buffalo.STLFile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
