# Generated by Django 3.0.7 on 2021-01-31 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buffalo', '0016_auto_20201216_0807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodlog',
            name='food',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='buffalo.FoodType'),
        ),
    ]
