username = 'db_user';
password = '';
datasource = "alyx";
conn = postgresql(datasource,username,password);

% Find all channels in Spock that were alive on April 15th 2017 but dead on May 15th 2017

% Set this variable with the monkey id
subject_nickname = 'snake'
date_alive = '2020-02-26'
date_dead = '2019-10-04'

% To query a date range: set and uncomment the following variables with the dates ranges:
% date_alive_start = '2020-02-25'
% date_alive_end = '2020-02-26'
% date_dead_start = '2019-10-03'
% date_dead_end = '2019-10-04'

% Then replace "'select be.channel_number ' ..." with "distinct( be.channel_number )"
% replace the first "'and date(asess.start_time) = ''%s'' ' ..." with "'and date(asess.start_time) between ''%s'' and ''%s'' ' ..."
% And replace the second "and date(asess_s.start_time) = ''%s'' ' ..." with "and date(asess_s.start_time)  between ''%s'' and ''%s'' '"
% Finally replace "], subject_nickname, date_alive, date_dead)" with "], subject_nickname, date_alive_start, date_alive_end, date_dead_start, date_dead_end)"

channels_sql = sprintf([
'select be.channel_number ' ...
'from buffalo_device bd, buffalo_electrode be, ' ...
'buffalo_buffalosubject bsub, buffalo_buffalosession bsess, ' ...
'actions_session asess, buffalo_channelrecording bch, subjects_subject ssub ' ...
'where ' ...
'ssub.nickname = ''%s'' ' ...
'and ssub.id = bsub.subject_ptr_id ' ...
'and asess.id = bsess.session_ptr_id ' ...
'and bsess.session_ptr_id = bch.session_id ' ...
'and bsub.subject_ptr_id = bd.subject_id ' ...
'and bd.id = be.device_id ' ...
'and bch.alive = ''yes'' ' ...
'and bch.electrode_id = be.id ' ...
'and date(asess.start_time) = ''%s'' ' ...
'and be.channel_number in ( ' ...
'	select be_s.channel_number ' ...
'	from buffalo_device bd_s, buffalo_electrode be_s, ' ...
'	buffalo_buffalosubject bsub_s, buffalo_buffalosession bsess_s, ' ...
'	actions_session asess_s, buffalo_channelrecording bch_s, subjects_subject ssub_s ' ...
'	where ' ...
'	ssub_s.id = ssub.id ' ...
'	and ssub_s.id = bsub_s.subject_ptr_id ' ...
'	and asess_s.id = bsess_s.session_ptr_id ' ...
'	and bsess_s.session_ptr_id = bch_s.session_id ' ...
'	and bsub_s.subject_ptr_id = bd_s.subject_id ' ...
'	and bd_s.id = be_s.device_id ' ...
'	and bch_s.alive = ''no'' ' ...
'	and bch_s.electrode_id = be_s.id ' ...
'	and date(asess_s.start_time) = ''%s'' ' ...
') '
], subject_nickname, date_alive, date_dead)

channels = fetch(conn, channels_sql);