username = 'database_user';
password = '';
datasource = "alyx";
conn = postgresql(datasource,username,password);

% Get a list of all channels with units in Spock in the hippocampus for 
% each day when we ran an ABA format Y-maze experiment in April 2017.

% Set this variable with the monkey id
subject_nickname = 'Lionel'
stl_name = 'hpc'
month = '10'
year = '2020'

channels_sql = sprintf([
'select be.channel_number ' ...
'from buffalo_device bd, buffalo_electrode be, buffalo_electrodelog bel, ' ...
'buffalo_electrodelogstl bels, buffalo_stlfile bstl, buffalo_buffalosubject bsub, ' ...
'data_dataset dset, buffalo_buffalosession bsess, buffalo_task btask, ' ...
'actions_session asess, buffalo_channelrecording bch, subjects_subject ssub ' ...
'where ' ...
'ssub.nickname = ''%s'' ' ...
'and ssub.id = bsub.subject_ptr_id ' ...
'and dset.name = ''%s'' ' ...
'and dset.id  = bstl.dataset_ptr_id ' ...
'and bd.subject_id = bsub.subject_ptr_id ' ...
'and bd.id = be.device_id ' ...
'and be.id = bel.electrode_id ' ...
'and bel.id = bels.electrodelog_id ' ...
'and date(bel.date_time) = date(asess.start_time) ' ...
'and bstl.dataset_ptr_id = bels.stl_id ' ...
'and bels.is_in is true ' ...
'and asess.id  = bsess.session_ptr_id ' ...
'and asess.id = bch.session_id ' ...
'and (bch.number_of_cells = ''3'' or bch.number_of_cells = ''4'') ' ...
'and date_part(''month'', date(asess.start_time)) = ''%s'' ' ...
'and date_part(''year'', date(asess.start_time)) = ''%s'' ' ...
'and asess.id in ' ...
'( ' ...
'	select session_id ' ...
'	from ' ...
'	( ' ...
'		select comp_query_a.session_id, comp_query_a.task_id, comp_query_a.task_name, ' ...
'		cast(comp_query_a.task_sequence as integer) - cast(comp_query_b.task_sequence as integer) diff ' ...
'		from ' ...
'		( '...
'			select asess.id session_id, btask.id task_id, btask.name task_name, bsessta.task_sequence task_sequence, ' ...
'			row_number() over(partition by asess.id, btask.id order by bsessta.task_sequence) gtask_seq ' ...
'			from buffalo_buffalosession bsess , actions_session asess, buffalo_sessiontask bsessta, ' ...
'			buffalo_task btask ' ...
'			where ' ...
'			asess.id = bsess.session_ptr_id ' ...
'			and bsessta.session_id = bsess.session_ptr_id ' ...
'			and btask.id = bsessta.task_id ' ...
'			order by asess.id, btask.id, bsessta.task_sequence ' ...
'		) comp_query_a, ' ...
'		( ' ...
'			select session_id, task_id, task_name, task_sequence, comp_query_int.gtask_seq + 1 gtask_next ' ...
'			from ' ...
'			( '...
'				select asess.id session_id , btask.id task_id, btask.name task_name, bsessta.task_sequence task_sequence, ' ...
'				row_number() over(partition by asess.id, btask.id order by bsessta.task_sequence) gtask_seq ' ...
'				from buffalo_buffalosession bsess , actions_session asess, buffalo_sessiontask bsessta, ' ...
'				buffalo_task btask ' ...
'				where ' ...
'				asess.id = bsess.session_ptr_id ' ...
'				and bsessta.session_id = bsess.session_ptr_id ' ...
'				and btask.id = bsessta.task_id ' ...
'				order by asess.id, btask.id, bsessta.task_sequence ' ...
'			) comp_query_int ' ...
'		) comp_query_b ' ...
'		where comp_query_a.gtask_seq = comp_query_b.gtask_next ' ...
'		and comp_query_a.session_id = comp_query_b.session_id ' ...
'		and comp_query_a.task_id = comp_query_b.task_id ' ...
'	) diff_query ' ...
'	where diff_query.diff = 2 ' ...
') ' ...
'group by be.channel_number '
], subject_nickname, stl_name, month, year)

channels = fetch(conn, channels_sql);